word_list = [
    'abruptly', 'absurd', 'abyss', 'affix', 'askew', 'avenue', 'awkward',
    'axiom', 'azure', 'bagpipes', 'bandwagon', 'banjo', 'bayou', 'beekeeper',
    'bikini', 'blitz', 'blizzard', 'boggle', 'bookworm', 'boxcar', 'boxful',
    'buckaroo', 'buffalo', 'buffoon', 'buxom', 'buzzard', 'buzzing', 'buzzwords',
    'cobweb', 'cockiness', 'croquet', 'crypt', 'curacao', 'cycle',
    'daiquiri', 'dirndl', 'disavow', 'dizzying', 'duplex', 'dwarves', 'embezzle',
    'equip', 'espionage', 'exodus', 'faking', 'fishhook', 'fixable',
    'fjord', 'flapjack', 'flopping', 'fluffiness', 'flyby', 'foxglove', 'frazzled',
    'frizzled', 'fuchsia', 'funny', 'gabby', 'galaxy', 'galvanize', 'gazebo',
    'gizmo', 'glowworm', 'glyph', 'gnarly', 'gossip',
    'grogginess', 'haiku', 'haphazard', 'hyphen', 'icebox', 'injury',
    'ivory', 'ivy', 'jackpot', 'jaundice', 'jawbreaker', 'jaywalk', 'jazziest',
    'jazzy', 'jelly', 'jigsaw', 'jinx', 'jiujitsu', 'jockey', 'jogging',
    'joking', 'jovial', 'joyful', 'juicy', 'jukebox', 'jumbo', 'kayak',
    'kazoo', 'keyhole', 'khaki', 'kilobyte', 'kiosk', 'kitsch', 'kiwifruit',
    'klutz', 'knapsack', 'mystify', 'nightclub', 'nowadays', 'numbskull', 'nymph',
    'onyx', 'ovary', 'oxidize', 'oxygen', 'pajama', 'peekaboo', 'phlegm',
    'pixel', 'pizazz', 'pneumonia', 'polka', 'pshaw', 'psyche', 'puppy',
    'puzzling', 'quartz', 'queue', 'quips', 'quixotic', 'quiz', 'quizzes',
    'quorum', 'razzmatazz', 'rhubarb', 'rhythm', 'rickshaw', 'schnapps', 'scratch',
    'snazzy', 'sphinx', 'spritz', 'squawk', 'staff', 'strength',
    'strengths', 'stretch', 'stronghold', 'stymied', 'subway', 'swivel', 'syndrome',
    'thriftless', 'thumbscrew', 'topaz', 'transcript', 'transgress', 'transplant',
    'twelfth', 'twelfths', 'unknown', 'unworthy', 'unzip', 'uptown', 'vaporize',
    'vixen', 'vodka', 'voodoo', 'vortex', 'walkway', 'waltz',
    'wave', 'wavy', 'waxy', 'wellspring', 'wheezy', 'whiskey', 'whizzing',
    'whomever', 'wimpy', 'witchcraft', 'wizard', 'woozy', 'wristwatch', 'wyvern',
    'xylophone', 'yachtsman', 'yippee', 'yoked', 'youthful', 'yummy', 'zephyr',
    'zigzag', 'zigzagging', 'zilch', 'zipper', 'zodiac', 'zombie'
]